[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026D4CEA8950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f0ea0fc78b8a7467ba20b29075342476/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026D4CE6A690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f0ea0fc78b8a7467ba20b29075342476/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026D4CE6A9C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f0ea0fc78b8a7467ba20b29075342476/element